##
## Plugin config template.
## This template file is manually curated for the particular OSA version
##
pluginVersion: v23.0
## List of RPM packages that fix security issues
securityPatchPackages: []
## Openshift component logging levels
componentLogLevel:
  apiServer: 2
  controllerManager: 2
  node: 2
## Change this for an address range using CIDR notation (e.g. 192.168.99.0/24); an IP address (e.g. 192.168.99.0);
## or a list of address ranges or IP addresses (e.g. 192.168.99.0/24,10.0.0.0/24,44.66.0.0/24)
## having access to system nodes: default (any ip address)
sshSourceAddressPrefixes: ["0.0.0.0/0"]
versions:
  v20.0:
    imageOffer: osa
    imagePublisher: redhat
    imageSku: osa_311
    imageVersion: 311.272.20200902
    images:
      alertManager: registry.access.redhat.com/openshift3/prometheus-alertmanager:v3.11.272
      ansibleServiceBroker: registry.access.redhat.com/openshift3/ose-ansible-service-broker:v3.11.272
      clusterMonitoringOperator: registry.access.redhat.com/openshift3/ose-cluster-monitoring-operator:v3.11.272
      configReloader: registry.access.redhat.com/openshift3/ose-configmap-reloader:v3.11.272
      console: registry.access.redhat.com/openshift3/ose-console:v3.11.272
      controlPlane: registry.access.redhat.com/openshift3/ose-control-plane:v3.11.272
      grafana: registry.access.redhat.com/openshift3/grafana:v3.11.272
      kubeRbacProxy: registry.access.redhat.com/openshift3/ose-kube-rbac-proxy:v3.11.272
      kubeStateMetrics: registry.access.redhat.com/openshift3/ose-kube-state-metrics:v3.11.272
      node: registry.access.redhat.com/openshift3/ose-node:v3.11.272
      nodeExporter: registry.access.redhat.com/openshift3/prometheus-node-exporter:v3.11.272
      oAuthProxy: registry.access.redhat.com/openshift3/oauth-proxy:v3.11.272
      prometheus: registry.access.redhat.com/openshift3/prometheus:v3.11.272
      prometheusConfigReloader: registry.access.redhat.com/openshift3/ose-prometheus-config-reloader:v3.11.272
      prometheusOperator: registry.access.redhat.com/openshift3/ose-prometheus-operator:v3.11.272
      registry: registry.access.redhat.com/openshift3/ose-docker-registry:v3.11.272
      registryConsole: registry.access.redhat.com/openshift3/registry-console:v3.11.272
      router: registry.access.redhat.com/openshift3/ose-haproxy-router:v3.11.272
      serviceCatalog: registry.access.redhat.com/openshift3/ose-service-catalog:v3.11.272
      templateServiceBroker: registry.access.redhat.com/openshift3/ose-template-service-broker:v3.11.272
      webConsole: registry.access.redhat.com/openshift3/ose-web-console:v3.11.272
      format: registry.access.redhat.com/openshift3/ose-${component}:v3.11.272
      httpd: registry.access.redhat.com/rhscl/httpd-24-rhel7:2.4-117.1593607199
      masterEtcd: registry.access.redhat.com/rhel7/etcd:3.2.28-23
      genevaLogging: osarpint.azurecr.io/acs/mdsd:master.20190228.1
      genevaStatsd: osarpint.azurecr.io/acs/mdm:git-a909a2e76
      genevaTDAgent: osarpint.azurecr.io/acs/td-agent:master.20190228.1
      logAnalyticsAgent: mcr.microsoft.com/azuremonitor/containerinsights/ciprod:ciprod08072020
      metricsServer: registry.access.redhat.com/openshift3/ose-metrics-server:v3.11.272
      azureControllers: osarpint.azurecr.io/openshift-on-azure/azure:v20.0
      aroAdmissionController: osarpint.azurecr.io/openshift-on-azure/azure:v20.0
      canary: osarpint.azurecr.io/openshift-on-azure/azure:v20.0
      etcdBackup: osarpint.azurecr.io/openshift-on-azure/azure:v20.0
      metricsBridge: osarpint.azurecr.io/openshift-on-azure/azure:v20.0
      startup: osarpint.azurecr.io/openshift-on-azure/azure:v20.0
      sync: osarpint.azurecr.io/openshift-on-azure/azure:v20.0
      tlsProxy: osarpint.azurecr.io/openshift-on-azure/azure:v20.0
  v21.0:
    imageOffer: osa
    imagePublisher: redhat
    imageSku: osa_311
    imageVersion: 311.346.20210118
    images:
      alertManager: registry.access.redhat.com/openshift3/prometheus-alertmanager:v3.11.346
      ansibleServiceBroker: registry.access.redhat.com/openshift3/ose-ansible-service-broker:v3.11.346
      clusterMonitoringOperator: registry.access.redhat.com/openshift3/ose-cluster-monitoring-operator:v3.11.346
      configReloader: registry.access.redhat.com/openshift3/ose-configmap-reloader:v3.11.346
      console: registry.access.redhat.com/openshift3/ose-console:v3.11.346
      controlPlane: registry.access.redhat.com/openshift3/ose-control-plane:v3.11.346
      grafana: registry.access.redhat.com/openshift3/grafana:v3.11.346
      kubeRbacProxy: registry.access.redhat.com/openshift3/ose-kube-rbac-proxy:v3.11.346
      kubeStateMetrics: registry.access.redhat.com/openshift3/ose-kube-state-metrics:v3.11.346
      node: registry.access.redhat.com/openshift3/ose-node:v3.11.346
      nodeExporter: registry.access.redhat.com/openshift3/prometheus-node-exporter:v3.11.346
      oAuthProxy: registry.access.redhat.com/openshift3/oauth-proxy:v3.11.346
      prometheus: registry.access.redhat.com/openshift3/prometheus:v3.11.346
      prometheusConfigReloader: registry.access.redhat.com/openshift3/ose-prometheus-config-reloader:v3.11.346
      prometheusOperator: registry.access.redhat.com/openshift3/ose-prometheus-operator:v3.11.346
      registry: registry.access.redhat.com/openshift3/ose-docker-registry:v3.11.346
      registryConsole: registry.access.redhat.com/openshift3/registry-console:v3.11.346
      router: registry.access.redhat.com/openshift3/ose-haproxy-router:v3.11.346
      serviceCatalog: registry.access.redhat.com/openshift3/ose-service-catalog:v3.11.346
      templateServiceBroker: registry.access.redhat.com/openshift3/ose-template-service-broker:v3.11.346
      webConsole: registry.access.redhat.com/openshift3/ose-web-console:v3.11.346
      format: registry.access.redhat.com/openshift3/ose-${component}:v3.11.346
      httpd: registry.access.redhat.com/rhscl/httpd-24-rhel7:2.4-133.1608869526
      masterEtcd: registry.access.redhat.com/rhel7/etcd:3.2.28-28
      genevaLogging: osarpint.azurecr.io/acs/mdsd:master.20190228.1
      genevaStatsd: osarpint.azurecr.io/acs/mdm:git-a909a2e76
      genevaTDAgent: osarpint.azurecr.io/acs/td-agent:master.20190228.1
      logAnalyticsAgent: mcr.microsoft.com/azuremonitor/containerinsights/ciprod:ciprod01112021
      metricsServer: registry.access.redhat.com/openshift3/ose-metrics-server:v3.11.346
      azureControllers: osarpint.azurecr.io/openshift-on-azure/azure:v21.0
      aroAdmissionController: osarpint.azurecr.io/openshift-on-azure/azure:v21.0
      canary: osarpint.azurecr.io/openshift-on-azure/azure:v21.0
      etcdBackup: osarpint.azurecr.io/openshift-on-azure/azure:v21.0
      metricsBridge: osarpint.azurecr.io/openshift-on-azure/azure:v21.0
      startup: osarpint.azurecr.io/openshift-on-azure/azure:v21.0
      sync: osarpint.azurecr.io/openshift-on-azure/azure:v21.0
      tlsProxy: osarpint.azurecr.io/openshift-on-azure/azure:v21.0
  v22.0:
    imageOffer: osa
    imagePublisher: redhat
    imageSku: osa_311
    imageVersion: 311.452.20210618
    images:
      alertManager: registry.access.redhat.com/openshift3/prometheus-alertmanager:v3.11.452
      ansibleServiceBroker: registry.access.redhat.com/openshift3/ose-ansible-service-broker:v3.11.452
      clusterMonitoringOperator: registry.access.redhat.com/openshift3/ose-cluster-monitoring-operator:v3.11.452
      configReloader: registry.access.redhat.com/openshift3/ose-configmap-reloader:v3.11.452
      console: registry.access.redhat.com/openshift3/ose-console:v3.11.452
      controlPlane: registry.access.redhat.com/openshift3/ose-control-plane:v3.11.452
      grafana: registry.access.redhat.com/openshift3/grafana:v3.11.452
      kubeRbacProxy: registry.access.redhat.com/openshift3/ose-kube-rbac-proxy:v3.11.452
      kubeStateMetrics: registry.access.redhat.com/openshift3/ose-kube-state-metrics:v3.11.452
      node: registry.access.redhat.com/openshift3/ose-node:v3.11.452
      nodeExporter: registry.access.redhat.com/openshift3/prometheus-node-exporter:v3.11.452
      oAuthProxy: registry.access.redhat.com/openshift3/oauth-proxy:v3.11.452
      prometheus: registry.access.redhat.com/openshift3/prometheus:v3.11.452
      prometheusConfigReloader: registry.access.redhat.com/openshift3/ose-prometheus-config-reloader:v3.11.452
      prometheusOperator: registry.access.redhat.com/openshift3/ose-prometheus-operator:v3.11.452
      registry: registry.access.redhat.com/openshift3/ose-docker-registry:v3.11.452
      registryConsole: registry.access.redhat.com/openshift3/registry-console:v3.11.452
      router: registry.access.redhat.com/openshift3/ose-haproxy-router:v3.11.452
      serviceCatalog: registry.access.redhat.com/openshift3/ose-service-catalog:v3.11.452
      templateServiceBroker: registry.access.redhat.com/openshift3/ose-template-service-broker:v3.11.452
      webConsole: registry.access.redhat.com/openshift3/ose-web-console:v3.11.452
      format: registry.access.redhat.com/openshift3/ose-${component}:v3.11.452
      httpd: registry.access.redhat.com/rhscl/httpd-24-rhel7:2.4-133.1608869526
      masterEtcd: registry.access.redhat.com/rhel7/etcd:3.2.28-28
      genevaLogging: osarpint.azurecr.io/acs/mdsd:master.20190228.1
      genevaStatsd: osarpint.azurecr.io/acs/mdm:git-a909a2e76
      genevaTDAgent: osarpint.azurecr.io/acs/td-agent:master.20190228.1
      logAnalyticsAgent: mcr.microsoft.com/azuremonitor/containerinsights/ciprod:ciprod01112021
      metricsServer: registry.access.redhat.com/openshift3/ose-metrics-server:v3.11.452
      azureControllers: osarpint.azurecr.io/openshift-on-azure/azure:v22.0
      aroAdmissionController: osarpint.azurecr.io/openshift-on-azure/azure:v22.0
      canary: osarpint.azurecr.io/openshift-on-azure/azure:v22.0
      etcdBackup: osarpint.azurecr.io/openshift-on-azure/azure:v22.0
      metricsBridge: osarpint.azurecr.io/openshift-on-azure/azure:v22.0
      startup: osarpint.azurecr.io/openshift-on-azure/azure:v22.0
      sync: osarpint.azurecr.io/openshift-on-azure/azure:v22.0
      tlsProxy: osarpint.azurecr.io/openshift-on-azure/azure:v22.0
  v23.0:
    imageOffer: osa
    imagePublisher: redhat
    imageSku: osa_311
    imageVersion: 311.452.20210618
    images:
      alertManager: registry.access.redhat.com/openshift3/prometheus-alertmanager:v3.11.452
      ansibleServiceBroker: registry.access.redhat.com/openshift3/ose-ansible-service-broker:v3.11.452
      clusterMonitoringOperator: registry.access.redhat.com/openshift3/ose-cluster-monitoring-operator:v3.11.452
      configReloader: registry.access.redhat.com/openshift3/ose-configmap-reloader:v3.11.452
      console: registry.access.redhat.com/openshift3/ose-console:v3.11.452
      controlPlane: registry.access.redhat.com/openshift3/ose-control-plane:v3.11.452
      grafana: registry.access.redhat.com/openshift3/grafana:v3.11.452
      kubeRbacProxy: registry.access.redhat.com/openshift3/ose-kube-rbac-proxy:v3.11.452
      kubeStateMetrics: registry.access.redhat.com/openshift3/ose-kube-state-metrics:v3.11.452
      node: registry.access.redhat.com/openshift3/ose-node:v3.11.452
      nodeExporter: registry.access.redhat.com/openshift3/prometheus-node-exporter:v3.11.452
      oAuthProxy: registry.access.redhat.com/openshift3/oauth-proxy:v3.11.452
      prometheus: registry.access.redhat.com/openshift3/prometheus:v3.11.452
      prometheusConfigReloader: registry.access.redhat.com/openshift3/ose-prometheus-config-reloader:v3.11.452
      prometheusOperator: registry.access.redhat.com/openshift3/ose-prometheus-operator:v3.11.452
      registry: registry.access.redhat.com/openshift3/ose-docker-registry:v3.11.452
      registryConsole: registry.access.redhat.com/openshift3/registry-console:v3.11.452
      router: registry.access.redhat.com/openshift3/ose-haproxy-router:v3.11.452
      serviceCatalog: registry.access.redhat.com/openshift3/ose-service-catalog:v3.11.452
      templateServiceBroker: registry.access.redhat.com/openshift3/ose-template-service-broker:v3.11.452
      webConsole: registry.access.redhat.com/openshift3/ose-web-console:v3.11.452
      format: registry.access.redhat.com/openshift3/ose-${component}:v3.11.452
      httpd: registry.access.redhat.com/rhscl/httpd-24-rhel7:2.4-133.1608869526
      masterEtcd: registry.access.redhat.com/rhel7/etcd:3.2.28-28
      genevaLogging: osarpint.azurecr.io/acs/mdsd:master.20190228.1
      genevaStatsd: osarpint.azurecr.io/acs/mdm:git-a909a2e76
      genevaTDAgent: osarpint.azurecr.io/acs/td-agent:master.20190228.1
      logAnalyticsAgent: mcr.microsoft.com/azuremonitor/containerinsights/ciprod:ciprod01112021
      metricsServer: registry.access.redhat.com/openshift3/ose-metrics-server:v3.11.452
      azureControllers: quay.io/openshift-on-azure/ci-azure:latest
      aroAdmissionController: quay.io/openshift-on-azure/ci-azure:latest
      canary: quay.io/openshift-on-azure/ci-azure:latest
      etcdBackup: quay.io/openshift-on-azure/ci-azure:latest
      metricsBridge: quay.io/openshift-on-azure/ci-azure:latest
      startup: quay.io/openshift-on-azure/ci-azure:latest
      sync: quay.io/openshift-on-azure/ci-azure:latest
      tlsProxy: quay.io/openshift-on-azure/ci-azure:latest
## certificates, used to authenticate to external systems
## Red Hat CDN client certificates
#packageRepository:
#  key: <Red Hat CDN client key value. Format: Base64 in YAML, rsa.PrivateKey in struct>
#  cert: <Red Hat CDN client certificate Format: Base64 in YAML, x509.Certificate struct>
## Geneva integration certificates. Example:
#certificates:
#genevaLogging:
#  key: <Geneva logging key value. Format: Base64 in YAML, rsa.PrivateKey in struct>
#  cert: <Geneva logging certificate Format: Base64 in YAML, x509.Certificate struct>
#genevaMetrics:
#  key: <Geneva metrics key value. Base64 in YAML, rsa.PrivateKey in struct>
#  cert: <Geneva metrics certificate value. Format: Base64 in YAML, x509.Certificate struct>
## Geneva integration other details
genevaLoggingSector: US-Test
genevaLoggingAccount: ccpopenshiftdiag
genevaLoggingNamespace: CCPOpenShift
genevaLoggingControlPlaneAccount: RPOpenShiftAccount
genevaLoggingControlPlaneEnvironment: Test
genevaLoggingControlPlaneRegion: eastus
genevaMetricsAccount: RPOpenShift
genevaMetricsEndpoint: https://az-int.metrics.nsatc.net/
## Container images used for specific OSA Cluster version
## Geneva image pull secret is used to access private component images. Format: base64 encoded .docker/config.json file "{auths:{osarpint.azurecr.io:{username:username,password:notthepasswordyouarelookingfor,email:openshift@example.com,auth:dXNlcm5hbWU6bm90dGhlcGFzc3dvcmR5b3VhcmVsb29raW5nZm9yCg==}}}"
#genevaImagePullSecret: <base64 string of .docker/config.json file>
## Image pull secret is used to pull images from private registries, used system-wide
#imagePullSecret: <base64 string of /var/lib/origin/.docker/config.json file>
